//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class CodigoPrototipo extends JPanel {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JLabel jcomp3;
    private JTextField Búsqueda;
    private JButton jcomp5;
    private JButton jcomp6;
    private JButton jcomp7;
    private JList jcomp8;
    private JComboBox Filtro;

    public CodigoPrototipo() {
        //construct preComponents
        String[] jcomp8Items = {"Item 1        Disponibilidad         Ubicación", "Item 2        Disponibilidad         Ubicación", "Item 3        Disponibilidad         Ubicación", "Item 4        Disponibilidad         Ubicación", "Item 5        Disponibilidad         Ubicación", "Item 6        Disponibilidad         Ubicación"};
        String[] FiltroItems = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6"};

        //construct components
        jcomp1 = new JLabel ("Sistema de reservas");
        jcomp2 = new JLabel ("Iniciar sesión");
        jcomp3 = new JLabel ("Ayuda");
        Búsqueda = new JTextField (5);
        jcomp5 = new JButton ("Inventario");
        jcomp6 = new JButton ("Reservas");
        jcomp7 = new JButton ("Administración");
        jcomp8 = new JList (jcomp8Items);
        Filtro = new JComboBox (FiltroItems);

        //set components properties
        Búsqueda.setToolTipText (".");

        //adjust size and set layout
        setPreferredSize (new Dimension (507, 295));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (Búsqueda);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);
        add (Filtro);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (5, 0, 140, 25);
        jcomp2.setBounds (425, 0, 100, 25);
        jcomp3.setBounds (465, 20, 100, 25);
        Búsqueda.setBounds (25, 105, 355, 25);
        jcomp5.setBounds (25, 55, 100, 25);
        jcomp6.setBounds (125, 55, 100, 25);
        jcomp7.setBounds (225, 55, 120, 25);
        jcomp8.setBounds (25, 125, 355, 125);
        Filtro.setBounds (25, 80, 355, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("CodigoPrototipo");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new CodigoPrototipo());
        frame.pack();
        frame.setVisible (true);
    }
}
